openapi: 3.0.1
info:
  title: Digimon Service API
  description: 提供孵化數碼蛋與培育等數碼寶貝養成服務
  version: 1.0.0
servers:
  - url: https://localhost/api/v1
paths:
  /digimons:
    post:
      summary: 產生數碼蛋
      description: 產生一顆數碼蛋，供request端養成
      requestBody:
        description: 客製數碼蛋的請求
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/DigimonInfoRequest"
      responses:
        200:
          description: 數碼蛋的資訊
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/DigimonInfo"
        500:
          $ref: "#/components/responses/500InternalError"
  /digimons/{digimonID}:
    get:
      summary: 查看數碼獸狀態
      parameters:
        - in: path
          name: digimonID
          schema:
            type: string
          required: true
          description: 數碼蛋的唯一識別碼，格式為uuid v4
      responses:
        200:
          description: 數碼蛋的資訊
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/DigimonInfo"
        500:
          $ref: "#/components/responses/500InternalError"
  /digimons/{digimonID}/foster:
    post:
      summary: 培育數碼獸
      description: 對數碼獸進行培育，以改善數碼獸的狀態
      parameters:
        - in: path
          name: digimonID
          schema:
            type: string
          required: true
          description: 數碼蛋的唯一識別碼，格式為uuid v4
      requestBody:
        description: 培育的食物
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/FosterRequest"
      responses:
        200:
          description: 培育完畢後的數碼獸的資訊
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/DigimonInfo"
        500:
          $ref: "#/components/responses/500InternalError"
components:
  schemas:
    DigimonInfo:
      type: object
      properties:
        id:
          type: string
          description: 數碼蛋的唯一識別碼，格式為uuid v4
          example: 56e400bd-c98b-49b9-ad8c-0607800e026f
        name:
          type: string
          description: 數碼蛋的名稱
          example: Agumon
        status:
          type: string
          description: 數碼蛋此時的狀態
          example: healthy
    FosterRequest:
      type: object
      properties:
        foot:
          type: object
          description: 培育所使用的食物
          properties:
            name:
              type: string
              description: 食物名稱
              example: apple
    DigimonInfoRequest:
      type: object
      properties:
        name:
          type: string
          description: 數碼蛋的名字
      required:
        - name
      example:
        name: Agumon
    Error:
      type: object
      properties:
        message:
          type: string
          description: 錯誤訊息
        code:
          type: number
          description: >
            錯誤代碼:
             * `3000` - Internal error
      required:
        - message
        - code
      example:
        message: "Internal error. Parsing failed"
        code: 3000
  responses:
    500InternalError:
      description: 伺服器錯誤
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Error"
